media:
  # Points to the media files in your repository's root.
  input: "."

  # References media files relative to the website's base URL.
  output: "."

  # The default path when opening the media browser.
  path: "/"

  # File extensions to display in the PagesCMS media browser.
  extensions:
    - png
    - jpg
    - jpeg
    - gif

  # Categories for organizing your media files.
  categories:
    - images
