media:
  # The folder in your repo where media files live.
  # Since your media (images, GIFs, etc.) are in the root, we use "."
  input: "."

  # The folder on your live site where media is served.
  # In this case, media is served from the site’s root, so we use "/"
  output: "/"

  # When the media browser opens in PagesCMS, it will default to the root.
  path: "/"

  # Only files with these extensions will appear in the media browser.
  extensions:
    - gif
    - jpg
    - jpeg
    - png

# This content section tells PagesCMS which file to treat as a managed page.
# In this example, we configure the homepage (index.html).
content:
  - name: homepage
    label: "Home"
    type: file
    # Path to the file relative to the repo root
    path: "index.html"
    # A Lucide icon name to show in the CMS sidebar (optional)
    icon: home
    # Set the format to "raw" if you are editing a plain HTML file.
    # (Other options include code, yaml-frontmatter, etc.)
    format: raw
